# Generated by Django 5.0.2 on 2024-02-15 16:03

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    (products.models.Category["TECH"], "TECH"),
                    (products.models.Category["COOKING"], "COOKING"),
                    (products.models.Category["TOYS"], "TOYS"),
                ],
                max_length=100,
            ),
        ),
    ]
