# Generated by Django 5.0.2 on 2024-02-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("TECH", "TECH"), ("COOKING", "COOKING"), ("TOYS", "TOYS")],
                max_length=100,
            ),
        ),
    ]
