# Generated by Django 5.0.2 on 2024-02-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("TECH", "TECH"),
                    ("COOKING", "COOKING"),
                    ("TOYS", "TOYS"),
                    ("FASHION", "FASHION"),
                ],
                max_length=100,
            ),
        ),
    ]
