# Generated by Django 5.0.2 on 2024-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
